services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      SPAWN_PROTECTION: 0
      DIFFICULTY: hard
      TYPE: MODRINTH
      MODRINTH_MODPACK: 1KVo5zza
    volumes:
      - ./data:/data
